
import React from 'react';

const Footer: React.FC = () => {
    return (
        <footer className="bg-transparent dark:bg-swalang-blue/30 mt-12 border-t border-swalang-light-border dark:border-swalang-purple transition-colors duration-300">
            <div className="container mx-auto px-4 py-6 text-center text-swalang-light-subtle dark:text-swalang-light">
                <p>&copy; {new Date().getFullYear()} Swalang Modules. A Fictional Project.</p>
                <p>Package data generated by Google Gemini.</p>
            </div>
        </footer>
    );
};

export default Footer;