-- Swalang Collaborate Supabase Schema
-- version 1.0.0

-- 1. PROFILES TABLE
-- Stores public user data, linked to the authentication system.
-- This table is automatically populated with a new user's ID
-- when they sign up, thanks to the trigger below.
CREATE TABLE public.profiles (
  id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text,
  updated_at timestamptz,

  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Trigger to create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (new.id, new.raw_user_meta_data->>'username');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 2. KEYWORDS TABLE
-- Stores the original English/Python keywords.
CREATE TABLE public.keywords (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  english_term text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now() NOT NULL,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  standardized_suggestion_id bigint -- This will be a foreign key after suggestions table is created
);

ALTER TABLE public.keywords ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Keywords are viewable by everyone." ON public.keywords FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create keywords." ON public.keywords FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- 3. SUGGESTIONS TABLE
-- Stores the Swahili suggestions for each keyword.
CREATE TABLE public.suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  keyword_id bigint NOT NULL REFERENCES public.keywords(id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  swahili_term text NOT NULL,
  description text NOT NULL,
  use_case_code text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Suggestions are viewable by everyone." ON public.suggestions FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create suggestions." ON public.suggestions FOR INSERT WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = author_id);
CREATE POLICY "Authors can update their own suggestions." ON public.suggestions FOR UPDATE USING (auth.uid() = author_id);
CREATE POLICY "Authors can delete their own suggestions." ON public.suggestions FOR DELETE USING (auth.uid() = author_id);

-- Now that suggestions table exists, add the foreign key constraint to keywords.
ALTER TABLE public.keywords
ADD CONSTRAINT fk_standardized_suggestion
FOREIGN KEY (standardized_suggestion_id)
REFERENCES public.suggestions(id) ON DELETE SET NULL;


-- 4. VOTES TABLE
-- Tracks individual votes to prevent duplicate voting.
CREATE TABLE public.votes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  suggestion_id bigint NOT NULL REFERENCES public.suggestions(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  vote_type smallint NOT NULL CHECK (vote_type IN (-1, 1)), -- -1 for downvote, 1 for upvote
  created_at timestamptz DEFAULT now() NOT NULL,

  -- A user can only vote once on a single suggestion
  CONSTRAINT unique_vote_per_user_per_suggestion UNIQUE (suggestion_id, user_id)
);

ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Votes are viewable by everyone." ON public.votes FOR SELECT USING (true);
CREATE POLICY "Authenticated users can cast votes." ON public.votes FOR INSERT WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);
CREATE POLICY "Users can change their own vote." ON public.votes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own vote." ON public.votes FOR DELETE USING (auth.uid() = user_id);


-- 5. OPTIONAL: VOTE COUNT FUNCTION
-- A database function to easily get the total votes for a suggestion.
-- This is more efficient than calculating it on the client side.
CREATE OR REPLACE FUNCTION public.get_suggestion_votes(suggestion_id_param bigint)
RETURNS int AS $$
  SELECT COALESCE(SUM(vote_type), 0)::int
  FROM public.votes
  WHERE suggestion_id = suggestion_id_param;
$$ LANGUAGE sql STABLE;