import { GoogleGenAI, Type } from "@google/genai";

// Fix: The `Package` type was previously imported from `types.ts` which is not a module.
// The type is now defined here, co-located with the schema that generates the data.
export interface Package {
    name: string;
    version: string;
    description: string;
    author: string;
    keywords: string[];
    readme: string;
}

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const packageSchema = {
    type: Type.OBJECT,
    properties: {
        name: { type: Type.STRING, description: "The name of the package, should be in kebab-case or snake_case." },
        version: { type: Type.STRING, description: "The semantic version of the package, e.g., '1.2.3'." },
        description: { type: Type.STRING, description: "A brief, one-sentence description of what the package does." },
        author: { type: Type.STRING, description: "The name of the package author or organization." },
        keywords: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "A list of relevant keywords or tags for the package."
        },
        readme: { type: Type.STRING, description: "A short, markdown-formatted README content. Include a brief introduction and a simple usage example in a Swalang code block (```swalang...```)." },
    },
    required: ["name", "version", "description", "author", "keywords", "readme"],
};

const responseSchema = {
    type: Type.ARRAY,
    items: packageSchema,
};

export const generatePackages = async (query: string): Promise<Package[]> => {
    const prompt = `
        You are a package generator for a fictional, modern programming language called "Swalang".
        Generate a list of 15 creative and plausible-sounding Swalang packages.
        For each package, include a short README in markdown format with an introduction and a simple Swalang code example.
        The package names and descriptions should sound authentic for a developer ecosystem.
        ${query ? `The packages should be related to the topic: "${query}".` : 'The packages should cover a range of common topics like web frameworks, data science, utilities, and graphics.'}
        Ensure the output is a valid JSON array matching the provided schema.
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: responseSchema,
                temperature: 0.8,
            },
        });
        
        const text = response.text;
        if (!text) {
            throw new Error("No content generated by Gemini.");
        }

        const jsonText = text.trim();
        const packages: Package[] = JSON.parse(jsonText);
        return packages;
    } catch (error) {
        console.error("Error generating packages with Gemini:", error);
        // Fallback or rethrow. Returning empty array to prevent app crash on build if env var is missing or API fails.
        return []; 
    }
};


export const generateDocumentation = async (topic: string): Promise<string> => {
    const prompt = `
        You are an expert technical writer for a fictional, modern programming language called "Swalang".
        Your task is to write a comprehensive and clear documentation page for the following topic: "${topic}".
        
        The documentation should be well-structured and easy for developers to understand.
        Use markdown formatting extensively.
        
        Include the following sections where appropriate:
        - A brief introduction to the topic.
        - Core concepts with clear explanations.
        - Swalang code examples in markdown code blocks (e.g., \`\`\`swalang ... \`\`\`). The code should be creative and plausible for the Swalang language.
        - Usage patterns and best practices.
        - Function or API signatures if applicable.
        
        Ensure the output is a single, complete markdown document.
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                temperature: 0.5,
            },
        });
        
        return response.text || "Documentation could not be generated.";
    } catch (error) {
        console.error(`Error generating documentation for topic "${topic}":`, error);
        return "Failed to generate documentation content.";
    }
};